# Generated by Django 2.0.4 on 2020-04-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20200401_2149'),
        ('core', '0002_pontoturistico_atracoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name': 'Ponto Turistico', 'verbose_name_plural': 'Pontos Turisticos'},
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
