# Generated by Django 2.0.4 on 2020-04-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name_plural': 'Comentarios'},
        ),
    ]
