# Generated by Django 2.0.4 on 2020-04-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20200401_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='aprovadp',
            new_name='aprovado',
        ),
    ]
