# Generated by Django 2.0.4 on 2020-04-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atracao',
            name='horario_funcionamento',
        ),
        migrations.RemoveField(
            model_name='atracao',
            name='idade_minima',
        ),
        migrations.AddField(
            model_name='atracao',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
