# Generated by Django 2.0.4 on 2020-04-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_auto_20200401_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name_plural': 'Atracoes'},
        ),
    ]
