# Generated by Django 2.0.4 on 2020-04-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0003_auto_20200401_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atracao',
            name='aprovado',
        ),
        migrations.AddField(
            model_name='atracao',
            name='horario_func',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atracao',
            name='idade_minima',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
